import * as THREE from './vendor/three.module.js';

const stage = document.querySelector('#game-stage'); const scoreEl = document.querySelector('#score'); const overlay = document.querySelector('#gameOver'); const label = document.querySelector('#result-label'); const title = document.querySelector('#result-title'); const restart = document.querySelector('#restart-btn');
const scene = new THREE.Scene(); scene.background = new THREE.Color(0x0c1330); scene.fog = new THREE.Fog(0x0c1330, 20, 105);
const camera = new THREE.PerspectiveCamera(58, 16 / 9, .1, 180); const renderer = new THREE.WebGLRenderer({ antialias: true }); renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); renderer.shadowMap.enabled = true; stage.prepend(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xb8c9ff, 0x11213d, 2)); const key = new THREE.DirectionalLight(0xffd5aa, 2.3); key.position.set(-6, 12, 5); key.castShadow = true; scene.add(key);
const road = new THREE.Mesh(new THREE.PlaneGeometry(15, 180), new THREE.MeshStandardMaterial({ color:0x24345d, roughness:.85 })); road.rotation.x=-Math.PI/2;road.position.z=-55;road.receiveShadow=true;scene.add(road);
for(let z=8;z>-145;z-=8){for(const x of [-2.25,2.25]){const stripe=new THREE.Mesh(new THREE.BoxGeometry(.08,.04,3.2),new THREE.MeshBasicMaterial({color:0x89e7e1}));stripe.position.set(x,.025,z);scene.add(stripe)} const marker=new THREE.Mesh(new THREE.BoxGeometry(.12,.05,1.4),new THREE.MeshBasicMaterial({color:0x5e76d5}));marker.position.set(0,.03,z);scene.add(marker)}
const player = new THREE.Group(); const body = new THREE.Mesh(new THREE.BoxGeometry(.9,1.05,.9), new THREE.MeshStandardMaterial({color:0x72e6cf,roughness:.35,metalness:.15}));body.position.y=.72;body.castShadow=true;player.add(body); const visor=new THREE.Mesh(new THREE.BoxGeometry(.58,.22,.05),new THREE.MeshStandardMaterial({color:0x13244f,emissive:0x243e89,emissiveIntensity:.7}));visor.position.set(0,.91,.47);player.add(visor);scene.add(player);
const lanes=[-1.45,0,1.45]; const obstacles=[]; const obstacleGeometry=new THREE.BoxGeometry(1,1.25,1); const obstacleMaterial=new THREE.MeshStandardMaterial({color:0xfb745f,roughness:.35,emissive:0x5f131a,emissiveIntensity:.35}); const playerBox=new THREE.Box3(), enemyBox=new THREE.Box3();
let state;
function addObstacle(lane,z){const mesh=new THREE.Mesh(obstacleGeometry,obstacleMaterial);mesh.position.set(lanes[lane],.63,z);mesh.castShadow=true;scene.add(mesh);obstacles.push(mesh)}
function resetGame(){obstacles.splice(0).forEach(mesh=>scene.remove(mesh));addObstacle(1,-21);addObstacle(0,-43);addObstacle(2,-66);addObstacle(0,-88); state={lane:1,distance:0,status:'playing',last:performance.now()};player.position.x=0;scoreEl.textContent='0';overlay.classList.add('hidden')}
function finish(won){if(state.status!=='playing')return;state.status=won?'won':'lost';label.textContent=won?'航线已完成':'空间碰撞';title.textContent=won?'已穿过天际门':'航道已中断';restart.textContent='重新启航';overlay.classList.remove('hidden')}
function move(delta){if(state.status!=='playing')return;state.lane=Math.max(0,Math.min(2,state.lane+delta))}
window.addEventListener('keydown',event=>{if(['ArrowLeft','a','A'].includes(event.key))move(-1);if(['ArrowRight','d','D'].includes(event.key))move(1);if(event.key===' '&&state.status!=='playing')resetGame()});document.querySelector('#left-zone').addEventListener('touchstart',event=>{event.preventDefault();move(-1)},{passive:false});document.querySelector('#right-zone').addEventListener('touchstart',event=>{event.preventDefault();move(1)},{passive:false});document.querySelector('#left-zone').addEventListener('click',()=>move(-1));document.querySelector('#right-zone').addEventListener('click',()=>move(1));restart.addEventListener('click',resetGame);
function resize(){const rect=stage.getBoundingClientRect();camera.aspect=rect.width/rect.height;camera.updateProjectionMatrix();renderer.setSize(rect.width,rect.height,false)}window.addEventListener('resize',resize);resize();
function animate(now){requestAnimationFrame(animate);const dt=Math.min(45,now-state.last);state.last=now;if(state.status==='playing'){state.distance+=dt*.09;player.position.x+= (lanes[state.lane]-player.position.x)*Math.min(1,dt*.012);player.rotation.z=(lanes[state.lane]-player.position.x)*-.2;player.position.y=.035+Math.abs(Math.sin(now*.009))*.045;obstacles.forEach(mesh=>mesh.position.z+=dt*.012);playerBox.setFromObject(player);for(const mesh of obstacles){enemyBox.setFromObject(mesh);if(playerBox.intersectsBox(enemyBox))finish(false)}if(state.distance>=1000)finish(true);scoreEl.textContent=Math.floor(state.distance)}camera.position.lerp(new THREE.Vector3(player.position.x*.34,5.0,8.5),.08);camera.lookAt(player.position.x*.18,.65,-9);renderer.render(scene,camera)}
resetGame();requestAnimationFrame(animate);window.__runner3d={resetGame,move,finish,getState:()=>({...state}),renderer,scene,camera};
