import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createServer } from 'node:http';
import { extname, join, normalize } from 'node:path';
import { chromium } from 'playwright';

const root = normalize(join(import.meta.dirname, '..'));
const type = { '.html':'text/html','.js':'text/javascript','.css':'text/css' };
async function server() { const app=createServer(async(req,res)=>{let path=decodeURIComponent(req.url.split('?')[0]);if(path.endsWith('/'))path+='index.html';const target=normalize(join(root,path));if(!target.startsWith(root)){res.writeHead(403);return res.end()}try{const body=await readFile(target);res.writeHead(200,{'content-type':type[extname(target)]||'application/octet-stream'});res.end(body)}catch{res.writeHead(404);res.end()}});await new Promise(r=>app.listen(0,'127.0.0.1',r));return app }
test('作品不包含运行时 CDN，并包含完整结构', async()=>{for(const dir of ['baseline-2d','skill-3d']){const html=await readFile(join(root,dir,'index.html'),'utf8');const game=await readFile(join(root,dir,'game.js'),'utf8');assert.match(html,/canvas|game-stage/);assert.match(game,/requestAnimationFrame/);assert.doesNotMatch(html,/https?:\/\//)}const three=await readFile(join(root,'skill-3d/vendor/three.module.js'),'utf8');const core=await readFile(join(root,'skill-3d/vendor/three.core.js'),'utf8');assert.match(three,/three\.js/);assert.match(core,/three\.js/)});
test('桌面与移动端可启动、移动、结束并重启', async()=>{const app=await server();let browser;try{const port=app.address().port;browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1100,height:760}});await page.goto(`http://127.0.0.1:${port}/skill-3d/`);await page.waitForFunction(()=>window.__runner3d?.renderer?.domElement instanceof HTMLCanvasElement);assert.equal(await page.evaluate(()=>window.__runner3d.getState().status),'playing');await page.keyboard.press('ArrowLeft');assert.equal(await page.evaluate(()=>window.__runner3d.getState().lane),0);await page.evaluate(()=>window.__runner3d.finish(false));await page.locator('#restart-btn').click();assert.equal(await page.evaluate(()=>window.__runner3d.getState().status),'playing');const mobile=await browser.newPage({viewport:{width:390,height:740},hasTouch:true});await mobile.goto(`http://127.0.0.1:${port}/skill-3d/`);await mobile.waitForFunction(()=>window.__runner3d);await mobile.locator('#right-zone').tap();assert.equal(await mobile.evaluate(()=>window.__runner3d.getState().lane),2);await mobile.close();await page.goto(`http://127.0.0.1:${port}/baseline-2d/`);await page.waitForFunction(()=>window.__runner2d);await page.locator('#restart').click();await page.keyboard.press('ArrowRight');assert.equal(await page.evaluate(()=>window.__runner2d.getState().lane),1)}finally{await browser?.close();app.closeAllConnections();await new Promise(resolve=>app.close(resolve))}});
test('真实障碍会触发碰撞结束，窗口变化会重设 3D 画布', async()=>{const app=await server();let browser;try{const port=app.address().port;browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1100,height:760}});await page.goto(`http://127.0.0.1:${port}/skill-3d/`);await page.waitForFunction(()=>window.__runner3d?.renderer);await page.waitForFunction(()=>window.__runner3d.getState().status==='lost',{timeout:3500});assert.equal(await page.evaluate(()=>window.__runner3d.getState().status),'lost');const before=await page.evaluate(()=>[window.__runner3d.renderer.domElement.width,window.__runner3d.renderer.domElement.height]);await page.setViewportSize({width:700,height:500});await page.waitForTimeout(150);const after=await page.evaluate(()=>[window.__runner3d.renderer.domElement.width,window.__runner3d.renderer.domElement.height]);assert.notDeepEqual(after,before)}finally{await browser?.close();app.closeAllConnections();await new Promise(resolve=>app.close(resolve))}});
