(() => {
  const canvas = document.querySelector('#game'); const ctx = canvas.getContext('2d');
  const overlay = document.querySelector('#overlay'); const title = document.querySelector('#result-title'); const label = document.querySelector('#result-label'); const restart = document.querySelector('#restart'); const scoreEl = document.querySelector('#score');
  const lanes = [-1, 0, 1]; let state;
  function reset() { state = { lane: 0, distance: 0, last: 0, status: 'playing', obstacles: [{ lane: 0, z: 510 }, { lane: -1, z: 770 }, { lane: 1, z: 930 }] }; overlay.classList.add('hidden'); scoreEl.textContent = '0'; }
  function end(won) { state.status = won ? 'won' : 'lost'; label.textContent = won ? '路线已完成' : '信标碰撞'; title.textContent = won ? '极光门已抵达' : '本次冲刺结束'; restart.textContent = '再跑一次'; overlay.classList.remove('hidden'); }
  function move(delta) { if (state.status === 'playing') state.lane = Math.max(-1, Math.min(1, state.lane + delta)); }
  window.addEventListener('keydown', e => { if (['ArrowLeft','a','A'].includes(e.key)) move(-1); if (['ArrowRight','d','D'].includes(e.key)) move(1); if (e.key === ' ' && state.status !== 'playing') reset(); }); restart.addEventListener('click', reset);
  function draw() { const w=canvas.width,h=canvas.height; ctx.clearRect(0,0,w,h); const sky=ctx.createLinearGradient(0,0,0,h); sky.addColorStop(0,'#0c4664');sky.addColorStop(.52,'#102d48');sky.addColorStop(1,'#081522');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h); ctx.fillStyle='#62e7c0';ctx.globalAlpha=.16;ctx.beginPath();ctx.arc(750,98,110,0,7);ctx.fill();ctx.globalAlpha=1;
    const horizon=168, bottom=560, center=w/2; ctx.fillStyle='#193d50';ctx.beginPath();ctx.moveTo(center-90,horizon);ctx.lineTo(center+90,horizon);ctx.lineTo(w,bottom);ctx.lineTo(0,bottom);ctx.fill(); for(let i=1;i<11;i++){let y=horizon+(bottom-horizon)*i/11;ctx.strokeStyle='#4c8695';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()} for(let l=-1;l<=1;l++){ctx.strokeStyle='#7bd8d1';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(center+l*28,horizon);ctx.lineTo(center+l*280,bottom);ctx.stroke()}
    state.obstacles.forEach(o=>{const d=Math.max(0,1-(o.z-state.distance)/520); if(d<0||d>1)return;const x=center+o.lane*(28+d*250),y=horizon+d*340,s=10+d*48;ctx.fillStyle='#fa6d62';ctx.fillRect(x-s/2,y-s,s,s);ctx.fillStyle='#ffd16d';ctx.fillRect(x-s*.23,y-s*.72,s*.46,s*.22)}); const px=center+state.lane*250,py=447;ctx.fillStyle='#58e6b5';ctx.fillRect(px-26,py-42,52,50);ctx.fillStyle='#eafcff';ctx.fillRect(px-14,py-59,28,22);ctx.fillStyle='#193d50';ctx.fillRect(px-7,py-53,14,6); }
  function tick(now) { if (!state.last) state.last=now; const dt=Math.min(40,now-state.last);state.last=now;if(state.status==='playing'){state.distance+=dt*.095; scoreEl.textContent=Math.floor(state.distance); for(const o of state.obstacles){if(Math.abs(o.z-state.distance)<18&&o.lane===state.lane)end(false)}if(state.distance>=1000)end(true)}draw();requestAnimationFrame(tick); }
  reset(); requestAnimationFrame(tick); window.__runner2d = { reset, move, getState: () => ({...state}) };
})();
